import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--mode', default="run", choices=["run", "debug"], help='choose the work mode, where the debug mode will generate all the intermediate files.')
parser.add_argument('--BGC', required=True, help='path of sequence fasta file to be searched.')
parser.add_argument('--if_spec', default=False, help='if include mass spectrum analysis.')
parser.add_argument('--mass_spec', help='path of the mass spectra file.')
parser.add_argument("--prob", help='path of the probability json file used for mass spectra.')
parser.add_argument('--model', choices=["Fisher", "MLE"], default="Fisher", help='path of the mass spectra file.')
parser.add_argument('--mon_cutoff', default="../data/monomer_hmm_cutoff.csv", help='path of monomer hmmsearch cutoff csv file.')
parser.add_argument('--mod_cutoff', default="../data/mod_hmm_cutoff.csv", help='path of modification hmmsearch cutoff csv file.')
parser.add_argument('--mon_hmm', default="../data/monomer_hmm", help='path of monomer hmm files.')
parser.add_argument('--mod_hmm', default="../data/modification_hmm", help='path of modification hmm files.')
parser.add_argument('--out_files', default = "", help='directory to store generated files.')
parser.add_argument('--connectivity', default="../data/connection_point.csv", help='path of monomer connectivity database.')
parser.add_argument('--BGClist', default="../data/train_BGC_list.csv", help='list of BGC names.')
parser.add_argument('--train_BGC_dir', default="../data/BGC", help='directory of BGC fasta files for MLE training')
parser.add_argument('--BGCbackbone', default="../data/BGC_backbone.csv", help='path of BGC backbone database.')
parser.add_argument('--length', default = 5, type = int, help='max length of predicted compounds\' chains.')
parser.add_argument('--mod_depth', default = 5, type = int, help='modification depth.')
parser.add_argument('--bond_list', default="../data/bond_data.txt", help='file of existing bonds.')
parser.add_argument('--mod_sif', default="../data/Seq2sachrriade_add4molecule.sif", help='sif file for adding modification through dereplicator')
parser.add_argument('--primary_mod_file', default="../data/primary_mod.txt", help='list of defined primary modification')
parser.add_argument('--gene_length', default = 3, type = int, help='min length of a gene to be recognized.')
parser.add_argument('--bond', type = int, default=0)
parser.add_argument('--primary_opt', type = int, default=2)
parser.add_argument('--set_num', type = int, default=500)

args = parser.parse_args()